export const types = {
  SET_LOADING: 'SET_LOADING',
  SET_GALLERY: 'SET_GALLERY',
  SET_IS_OPEN: 'SET_IS_OPEN',
  SET_PAGE: 'SET_PAGE',
  SET_PER_PAGE: 'SET_PER_PAGE',
  SET_Q: 'SET_Q',
  SET_CURRENT_IMG: 'SET_CURRENT_IMG',
  SET_ERROR: 'SET_ERROR',
  SET_MAX_IMG: 'SET_MAX_IMG',
};
